workspace(
    name = "rules_ruby_example",
    managed_directories = {"@bundle": ["vendor"]},
)

# Importing rules_ruby from the parent directory for developing
# rules_ruby itself...
local_repository(
    name = "rules_ruby",
    path = "../..",
)

load("@rules_ruby//ruby:deps.bzl", "rules_ruby_dependencies", "rules_ruby_register_toolchains")

rules_ruby_dependencies()

rules_ruby_register_toolchains(["ruby-2.7.1"])

load("@rules_ruby//ruby:defs.bzl", "ruby_bundle")

ruby_bundle(
    name = "bundle",
    bundler_version = "2.1.2",
    excludes = {
        "mini_portile": ["test/**/*"],
    },
    gemfile = "//:Gemfile",
    gemfile_lock = "//:Gemfile.lock",
    vendor_cache = True,
)
