# frozen_string_literal: true

source 'https://rubygems.org'

gem 'awesome_print'
gem 'colored2'
gem 'rspec', '~> 3.7.0'
gem 'rspec-its', github: "rspec/rspec-its", ref: "3d36b4a7b004ffa204a0e392f27c8b6b0b674ecf" # v1.3.0
gem 'rubocop'
