workspace(name = "bazelruby_ruby_rules_example")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Importing rules_ruby from the parent directory for developing
# rules_ruby itself...
local_repository(
    name = "bazelruby_ruby_rules",
    path = "../..",
)

load(
    "@bazelruby_ruby_rules//ruby:deps.bzl",
    "ruby_register_toolchains",
    "ruby_rules_dependencies",
)

ruby_rules_dependencies()

ruby_register_toolchains(version = "2.6.5")

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

### Pkg Utilities such as pkg_zip and pkg_tar
http_archive(
    name = "rules_pkg",
    sha256 = "4ba8f4ab0ff85f2484287ab06c0d871dcb31cc54d439457d28fd4ae14b18450a",
    url = "https://github.com/bazelbuild/rules_pkg/releases/download/0.2.4/rules_pkg-0.2.4.tar.gz",
)

load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")

rules_pkg_dependencies()

load(
    "@bazelruby_ruby_rules//ruby:defs.bzl",
    "ruby_gemset",
)

ruby_gemset(
    name = "gem_set",
    gem_home = "lib/gems",
    gems = {
        "awesome_print": "1.8.0",
        "colored2": "3.1.2",
        "rspec": "3.7.0",
        "rspec-its": "1.3.0",
        "rubocop": "0.78.0",
    },
    rubygems_sources = ["https://rubygems.org"],
)

ruby_bundle(
    name = "bundle",
    bundler_version = "2.1.2",
    gemfile = "//:Gemfile",
    gemfile_lock = "//:Gemfile.lock",
)
