workspace(name = "bazelruby_ruby_rules_example")

# Importing rules_ruby from the parent directory for developing
# rules_ruby itself...
local_repository(
    name = "bazelruby_ruby_rules",
    path = "..",
)

# But you'd usually want to fetch rules_ruby from remote.
#
# git_repository(
#     name = "bazelruby_ruby_rules",
#     remote = "https://github.com/yugui/rules_ruby.git",
#     tag = "v0.1.0",`
# )

load(
    "@bazelruby_ruby_rules//ruby:deps.bzl",
    "ruby_register_toolchains",
    "ruby_rules_dependencies",
)

ruby_rules_dependencies()

ruby_register_toolchains()

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

load("@bazelruby_ruby_rules//ruby:defs.bzl", "bundle_install")

bundle_install(
    name = "foo-bar-bundle",
    gemfile = "//apps/foo-bar:Gemfile",
    gemfile_lock = "//apps/foo-bar:Gemfile.lock",
)
