workspace(name = "com_github_yugui_rules_ruby_examples")

local_repository(
    name = "com_github_yugui_rules_ruby",
    path = "../",
)

load("@com_github_yugui_rules_ruby//ruby:def.bzl", "ruby_register_toolchains")

ruby_register_toolchains()
