workspace(name = "bazelruby_rules_ruby_example_gem")

# Importing rules_ruby from the parent directory for developing
# rules_ruby itself...
local_repository(
    name = "bazelruby_rules_ruby",
    path = "../..",
)

load(
    "@bazelruby_rules_ruby//ruby:deps.bzl",
    "rules_ruby_dependencies",
    "rules_ruby_select_sdk",
)

rules_ruby_dependencies()

rules_ruby_select_sdk("3.0.2")

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()
