workspace(name = "rules_ruby_example")

# Importing rules_ruby from the parent directory for developing
# rules_ruby itself...
local_repository(
    name = "rules_ruby",
    path = "../..",
)

load("@rules_ruby//ruby:deps.bzl", "rules_ruby_dependencies")

rules_ruby_dependencies()

load("@rules_ruby//ruby:deps.bzl", "rules_ruby_register_toolchains")

rules_ruby_register_toolchains(["ruby-3.0"])

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

load("@rules_ruby//ruby:defs.bzl", "ruby_bundle")

ruby_bundle(
    name = "bundle",
    gemfile = "//:Gemfile",
    gemfile_lock = "//:Gemfile.lock",
)
