workspace(name = "bazelrules_ruby_ruby_example")

# Importing rules_ruby from the parent directory for developing
# rules_ruby itself...
local_repository(
    name = "bazelrules_ruby_ruby",
    path = "../..",
)

load(
    "@bazelrules_ruby_ruby//ruby:deps.bzl",
    "ruby_register_toolchains",
    "rules_ruby_dependencies",
)

rules_ruby_dependencies()

ruby_register_toolchains(version = "2.7.0")

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

load("@bazelrules_ruby_ruby//ruby:defs.bzl", "bundle_install")

bundle_install(
    name = "bundle",
    gemfile = "//:Gemfile",
    gemfile_lock = "//:Gemfile.lock",
)
