workspace(name = "bazelruby_rules_ruby_ruby_tests_testdata_bundle_includes_workspace")

local_repository(
    name = "bazelruby_rules_ruby",
    path = "../../../..",
)

load(
    "@bazelruby_rules_ruby//ruby:deps.bzl",
    "rules_ruby_dependencies",
    "rules_ruby_select_sdk",
)

rules_ruby_dependencies()

rules_ruby_select_sdk(version = "3.0.1")

load("@bazelruby_rules_ruby//ruby:defs.bzl", "ruby_bundle")

ruby_bundle(
    name = "gems",
    bundler_version = "2.2.21",
    gemfile = "//:Gemfile",
    gemfile_lock = "//:Gemfile.lock",
    includes = {
        # The gemspec of grpc gem lists ['src/ruby/bin', 'src/ruby/lib', 'src/ruby/pb'] as the `require_paths`. When installing
        # pre-built versions of the gem, these are sufficient. However, when installing it from source, 'etc/roots.pem', a file
        # required by 'src/ruby/lib/grpc.rb', also needs to be present in the `$LOAD_PATH`. Thus users have to manually add the
        # 'etc' directory to the `$LOAD_PATH` using the `includes` option of `ruby_bundle` rule.
        "grpc": ["etc"],
    },
)
